### ISSUE TITLE
Set up geoCML documentation scaffolding

### ISSUE THREAD

**Issue by TristanDamron** [geoCML/docs#1]
We need to provide user documentation for geoCML to enable users to quickly become productive with their deployments. I suggest that we create a separate repo in this organization to hold our documentation source code and add it to this repo as a submodule! 

@capsulecorplab will be helping to develop a methodology/tool chain to use for our documentation. Once we've set up a structure for our docs, we will be adopting a docs-driven-development practice for geoCML.

**Comment by capsulecorplab** [comment]
Makes sense. We can also add it as part of the persistence layer so that the documentation is available locally within the kasm session

**Comment by capsulecorplab** [comment]
blocked on #2
